### PR TITLE
Update about page

### LINKED ISSUE #107: Update about us
move Mark (and others) to "Alumni devs"

### PR DESCRIPTION
**Pull request by whonore**
Fix #107

### CODE REVIEW

**Comment by whonore** [comment]
@tiffanywschan could you look at config/initializers/devs.rb and let me know what to put where I have `?`. And also if there's anyone I'm missing, if something's misspelled, etc.

**Comment by whonore** [comment]
@chloefink ping

**Comment by chloefink** [comment]
Could you update the email at the bottom of all the pages to be admin@newhavenhelpwithcovid.com instead of the old email. Otherwise it looks good to me. Honors last name is Thompson

**Comment by whonore** [comment]
Thanks, and Honor and Aria's position titles?

**Comment by chloefink** [comment]
Marketing and Communications Officer (for both of them)

**Pull request merged**
